import os
from dotenv import load_dotenv

load_dotenv()  # load from .env

SHOE_IMAGES_FOLDER = os.getenv("SHOE_IMAGES_FOLDER")
FAISS_INDEX_PATH = os.getenv("FAISS_INDEX_PATH")
EMBEDDING_META_INDEX=os.getenv("EMBEDDING_META_INDEX")
SHOE_PRODUCT_JSON_PATH=os.getenv("SHOE_PRODUCT_JSON_PATH")
IMAGE_PATHS_JSON=os.getenv("IMAGE_PATHS_JSON")

FAISS_HYBRID_INDEX_PATH = os.getenv("FAISS_HYBRID_INDEX_PATH")
EMBEDDING_META_HYBRID_INDEX=os.getenv("EMBEDDING_META_HYBRID_INDEX")
KMEANS_MODEL_PATH=os.getenv("KMEANS_MODEL_PATH")